Add GFF align tool
abims-sbr/tools-abims pull request #3
Opened 2020-11-13 08:17 UTC by RomainDallet

2020-11-13 08:35 UTC, lecorguille requested changes

2020-11-13 08:35 UTC, lecorguille commented on tools/gff-align/GFFalign.xml
> +        <param argument="t" type="integer" value="30" label="Interval" help="Interval, in nucleotide, within a gene is considered in the same position." />
You should have `argument="-t"`

2020-11-13 08:35 UTC, lecorguille commented on tools/gff-align/GFFalign.xml
> +<tool id="gff_align" name="GFF align" version="0.1.0" python_template_version="3.5">
It should be `version="0.1.0+galaxy0"`

2020-11-13 08:35 UTC, lecorguille commented on tools/gff-align/GFFalign.xml
> +        $targetGFF
Simple quote here

2020-11-18 08:14 UTC, lecorguille commented
Do you create a `.shed.yml` with `owner: abims-sbr`?
Otherwise, the tool isn't tested :/

2020-11-18 08:15 UTC, lecorguille requested changes
Do you create a `.shed.yml` with `owner: abims-sbr`?
Otherwise, the tool isn't tested :/

2020-11-18 09:12 UTC, RomainDallet commented
I think it's good for the `.shed.yml` file

2020-11-18 15:26 UTC, lecorguille requested changes

2020-11-18 15:26 UTC, lecorguille commented on tools/gff-align/GFFalign.xml
> +        <!--<param arg="-e" type="boolean" checked="false" truevalue="-extract" falsevalue="" label="Extract" help="Extract the fasta sequence of the new suggested gene. It takes two argument: the fa
arg -> argument

2020-11-18 15:26 UTC, lecorguille commented on tools/gff-align/GFFalign.xml
> +        <!--<param arg="-e" type="boolean" checked="false" truevalue="-extract" falsevalue="" label="Extract" help="Extract the fasta sequence of the new suggested gene. It takes two argument: the fa
You have to implement this param and its output

2020-11-18 15:26 UTC, lecorguille commented on tools/gff-align/GFFalign.xml
> +-->
You have to reintegrate this and add them in your test

2020-11-18 15:26 UTC, lecorguille commented on tools/gff-align/GFFalign.xml
> +        python3 $__tool_directory__/GFFalign.py
Simple quotes here

2020-11-20 15:38 UTC, lecorguille requested changes

2020-11-20 15:38 UTC, lecorguille commented on tools/gff-align/GFFalign.xml
> +            -e $e 'extracted_sequence.fa'
C'est bien beau mais où est la gestion de l'output dans `<outputs>` ?

Pour te faire gagner du temps, la réponse à ta futur question est là : https://docs.galaxyproject.org/en/latest/dev/schema.html#tool-outputs-data-filter

2020-11-20 15:38 UTC, lecorguille commented on tools/gff-align/GFFalign.xml
> +            -e $e 'extracted_sequence.fa'
Autant ne pas fixer le filename mais laisser Galaxy gérer avec `<data>`

2020-11-20 15:38 UTC, lecorguille commented on tools/gff-align/GFFalign.xml
> +            <param name="extract_fasta" type="boolean" checked="false" label="Extract fasta sequence of the new suggested gene" help="This option needs the fasta file of the genome. This will slow do
Les best practices IUC préconisent un `type="select"` que `boolean` si il y a un `conditional` en jeu

2020-11-23 10:22 UTC, RomainDallet commented on tools/gff-align/GFFalign.xml
> +            -e $e 'extracted_sequence.fa'
Les tests passent, je pense que c'est ok!

2020-11-23 10:37 UTC, lecorguille requested changes

2020-11-23 10:37 UTC, lecorguille commented on tools/gff-align/GFFalign.xml
>                  <param argument="-e" type="data" format="fasta" optional="true" label="Fasta file of the genome."/>
Pourquoi optional ?
Je pense que ça va pas le faire si un utilisateur ne donne pas de fichier fasta.

2020-11-23 10:37 UTC, lecorguille commented on tools/gff-align/GFFalign.xml
> +            <filter>options['extract_fasta'] == 'true' and options['e']</filter>
`options['extract_fasta']` devrait suffire si le fasta n'est pas `optional`

2020-11-23 10:54 UTC, RomainDallet commented on tools/gff-align/GFFalign.xml
>                  <param argument="-e" type="data" format="fasta" optional="true" label="Fasta file of the genome."/>
En effet. Je n'avais pas pensé à l'enlever. Ca devrait être bon du coup

2020-11-23 11:19 UTC, lecorguille approved these changes

2020-11-23 14:42 UTC, merged